# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/humble-chuck',
                'doc_host': 'https://schlinkertc@gmail.com.github.io',
                'git_url': 'https://github.com/schlinkertc@gmail.com/humble-chuck',
                'lib_path': 'humble_chuck'},
  'syms': {'humble_chuck.core': {'humble_chuck.core.foo': ('core.html#foo', 'humble_chuck/core.py')}}}
