# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_models.ipynb.

# %% auto 0
__all__ = ['model_dump_for_display', 'BaseModel']

# %% ../nbs/06_models.ipynb 3
from pydantic import BaseModel as PydanticBaseModel
from pydantic import ConfigDict
import logging
from json2html import json2html
from humble_chuck.delegation import delegates
from typing import *

# %% ../nbs/06_models.ipynb 6
@delegates(PydanticBaseModel.model_dump) 
def model_dump_for_display(
    model:PydanticBaseModel, #The model to by displayed
    **kwargs
):
    """Calls PydanticBaseModel.model_dump(), 
    but if there is an issue it raises a warning and passes to allow default representation.  

    Delegates kwargs to PydanticBaseModel.model_dump
    """
    kwargs['mode']='json'
    try:
        return model.model_dump(**kwargs)
    except Exception as e:
        logging.warning(e)
        pass

# %% ../nbs/06_models.ipynb 8
class BaseModel(PydanticBaseModel):
    
    def _repr_json_(self):
        return model_dump_for_display(
            self,
            mode='json',
            **self.model_config.get('repr_kwargs',{})
        )

    def _repr_html_(self):
        
        return json2html.convert(
            model_dump_for_display(self,mode='json',**self.model_config.get('repr_kwargs',{}))
        )
