project:
  type: website

format:
  html:
    theme: yeti
    css: styles.css
    page-layout: full
    link-external-newwindow: True
    toc: true
    keep-md: true
  #commonmark: default

website:
  twitter-card: false
  open-graph: false
  #repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    collapse-level: 1
    style: docked

metadata-files: [nbdev.yml, sidebar.yml]