project:
  type: website

format:
  html:
    theme: yeti
    grid: 
      sidebar-width: 20px
      body-width: 1500px
      margin-width: 250px
    css: styles.css
    page-layout: full
    link-external-newwindow: True
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: docked

metadata-files: [nbdev.yml, sidebar.yml]