project:
  type: website

format:
  html:
    theme: yeti
    # grid: 
    #   sidebar-width: 25px
      # body-width: 2000px
      # margin-width: 25px
    css: styles.css
    page-layout: article
    embed-resources: true
    link-external-newwindow: True
    toc: true
    toc-expand: false
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: docked

metadata-files: [nbdev.yml, sidebar.yml]