name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - uses: fastai/workflows/quarto-ghp@master
