name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - uses: actions/checkout@v3

      - uses: fastai/workflows/nbdev-ci@master
